apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops4expense-ArgoCD-test-1-application
  namespace: devops4expense
spec:
  project: default

  source:
    repoURL: https://github.com/Snuffules/argocd-app-config.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: devops4expense

    automated:
      selfHeal: true
      prune: true
