apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops4expense-ArgoCD-test-1
spec:
  selector:
    matchLabels:
      app: devops4expense-ArgoCD-test-1
  replicas: 2
  template:
    metadata:
      labels:
        app: devops4expense-ArgoCD-test-1
    spec:
      containers:
      - name: devops4expense-ArgoCD-test-1
        image: snuffules/ultimate-cicd:1.0
        ports:
        - containerPort: 8080
