apiVersion: v1
kind: Service
metadata:
  name: devops4expense-argocd-test-1
spec:
  selector:
    app: devops4expense-ArgoCD-test-1
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
